### ISSUE TITLE
Plane pitches downward when flaps are extended

### ISSUE THREAD

**Issue by iiRevzz** [GeoFS-Autoland/autoland#13]
**Describe the bug**
When you are lowering your flaps, the plane will slant downwards, while still going forwards, and be short of the runway. I noticed this in the last verseion too.

**To Reproduce**
1. Lower flaps to full.
2. See error

**Expected behavior**
I expected the plane to stay  facing upwards like if a pilot were flying.

**Actual behavior**
The plane tilted slightly downwards (still going straight), but is short of runway.
**Screenshots**
https://prnt.sc/1jze9uy
**Desktop (please complete the following information):**

- OS: Windows 10]
- Browser Chrome
- Version 92.0.4515.131

**Comment by nicolas377** [comment]
I don't think this is something we can really fix. This is probably something coming from ap++. Naturally, when the flaps come out more, the plane will tilt downward. Is ap++ pitching up to compensate?

**Comment by nicolas377** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plane pitches downward when flaps are extended](https://trello.com/c/11DDO2xW/21-plane-pitches-downward-when-flaps-are-extended)

**Comment by iiRevzz** [comment]
No, the plane just continues to stay slanted downward.

**Comment by nicolas377** [comment]
I think that's normal behaviour, but I'll check it out.

**Comment by nicolas377** [comment]
This is a problem with the route you were using
