### ISSUE TITLE
Changes to user prefs don't immediately take effect

### ISSUE THREAD

**Issue by iiRevzz** [GeoFS-Autoland/autoland#16]
**Describe the bug**
If you are in GeoFS, and enable ap+ and fmc in extension, you have to reload the page for it to show up in the game

**To Reproduce**
Enable ap+ and fmc in extension, nothing will happen unless you reload the page while on geofs.

**Expected behavior**
To load ap+ and fmc without having to reload

**Actual behavior**
Must reload before it loads into geofs

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 92.0.4515.131

**Comment by nicolas377** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Changes to user prefs don't immediately take effect](https://trello.com/c/QUmLcTIq/23-changes-to-user-prefs-dont-immediately-take-effect)

**Comment by Guy-Adler** [comment]
Will be added on beta 3.1.

**Comment by nicolas377** [comment]
Might end up being in a patch, or 3.1.0

**Comment by nicolas377** [comment]
The solution to this is working in internal beta, and will be released along with 3.0.2.
