### ISSUE TITLE
BUG: Sometimes FMC doesn't load

### ISSUE THREAD

**Issue by Guy-Adler** [GeoFS-Autoland/autoland#26]
**Describe the bug**
Sometimes the FMC script gets injected before ap++, causing FMC to not load.

**Comment by Guy-Adler** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sometimes FMC doesn't load](https://trello.com/c/8CLq2cYL/53-sometimes-fmc-doesnt-load)

**Comment by nicolas377** [comment]
Fixed in fb89318
